# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Analysis
version:      0.03
version_from: lib/Net/Analysis.pm
installdirs:  site
requires:
    LWP:                           0
    Net::Pcap:                     0
    NetPacket:                     0
    Params::Validate:              0
    Test::MockObject:              0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
